// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Action;
import intranet.ActionDataOnDemand;
import intranet.ActionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActionIntegrationTest: @Transactional;
    
    @Autowired
    private ActionDataOnDemand ActionIntegrationTest.dod;
    
    @Test
    public void ActionIntegrationTest.testCountActions() {
        Assert.assertNotNull("Data on demand for 'Action' failed to initialize correctly", dod.getRandomAction());
        long count = Action.countActions();
        Assert.assertTrue("Counter for 'Action' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActionIntegrationTest.testFindAction() {
        Action obj = dod.getRandomAction();
        Assert.assertNotNull("Data on demand for 'Action' failed to initialize correctly", obj);
        Integer id = obj.getIdaction();
        Assert.assertNotNull("Data on demand for 'Action' failed to provide an identifier", id);
        obj = Action.findAction(id);
        Assert.assertNotNull("Find method for 'Action' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Action' returned the incorrect identifier", id, obj.getIdaction());
    }
    
    @Test
    public void ActionIntegrationTest.testFindAllActions() {
        Assert.assertNotNull("Data on demand for 'Action' failed to initialize correctly", dod.getRandomAction());
        long count = Action.countActions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Action', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Action> result = Action.findAllActions();
        Assert.assertNotNull("Find all method for 'Action' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Action' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActionIntegrationTest.testFindActionEntries() {
        Assert.assertNotNull("Data on demand for 'Action' failed to initialize correctly", dod.getRandomAction());
        long count = Action.countActions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Action> result = Action.findActionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Action' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Action' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Action' failed to initialize correctly", dod.getRandomAction());
        Action obj = dod.getNewTransientAction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Action' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Action' identifier to be null", obj.getIdaction());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Action' identifier to no longer be null", obj.getIdaction());
    }
    
    @Test
    public void ActionIntegrationTest.testRemove() {
        Action obj = dod.getRandomAction();
        Assert.assertNotNull("Data on demand for 'Action' failed to initialize correctly", obj);
        Integer id = obj.getIdaction();
        Assert.assertNotNull("Data on demand for 'Action' failed to provide an identifier", id);
        obj = Action.findAction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Action' with identifier '" + id + "'", Action.findAction(id));
    }
    
}
