// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.AppConfig;
import intranet.AppConfigDataOnDemand;
import intranet.AppConfigIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppConfigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppConfigIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppConfigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppConfigIntegrationTest: @Transactional;
    
    @Autowired
    private AppConfigDataOnDemand AppConfigIntegrationTest.dod;
    
    @Test
    public void AppConfigIntegrationTest.testCountAppConfigs() {
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to initialize correctly", dod.getRandomAppConfig());
        long count = AppConfig.countAppConfigs();
        Assert.assertTrue("Counter for 'AppConfig' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppConfigIntegrationTest.testFindAppConfig() {
        AppConfig obj = dod.getRandomAppConfig();
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to initialize correctly", obj);
        Integer id = obj.getAppConfig();
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to provide an identifier", id);
        obj = AppConfig.findAppConfig(id);
        Assert.assertNotNull("Find method for 'AppConfig' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppConfig' returned the incorrect identifier", id, obj.getAppConfig());
    }
    
    @Test
    public void AppConfigIntegrationTest.testFindAllAppConfigs() {
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to initialize correctly", dod.getRandomAppConfig());
        long count = AppConfig.countAppConfigs();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppConfig', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppConfig> result = AppConfig.findAllAppConfigs();
        Assert.assertNotNull("Find all method for 'AppConfig' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppConfig' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppConfigIntegrationTest.testFindAppConfigEntries() {
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to initialize correctly", dod.getRandomAppConfig());
        long count = AppConfig.countAppConfigs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppConfig> result = AppConfig.findAppConfigEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppConfig' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppConfig' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppConfigIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to initialize correctly", dod.getRandomAppConfig());
        AppConfig obj = dod.getNewTransientAppConfig(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppConfig' identifier to be null", obj.getAppConfig());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AppConfig' identifier to no longer be null", obj.getAppConfig());
    }
    
    @Test
    public void AppConfigIntegrationTest.testRemove() {
        AppConfig obj = dod.getRandomAppConfig();
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to initialize correctly", obj);
        Integer id = obj.getAppConfig();
        Assert.assertNotNull("Data on demand for 'AppConfig' failed to provide an identifier", id);
        obj = AppConfig.findAppConfig(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppConfig' with identifier '" + id + "'", AppConfig.findAppConfig(id));
    }
    
}
