// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.AppFilter;
import intranet.AppFilterDataOnDemand;
import intranet.AppFilterIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppFilterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppFilterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppFilterIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppFilterIntegrationTest: @Transactional;
    
    @Autowired
    private AppFilterDataOnDemand AppFilterIntegrationTest.dod;
    
    @Test
    public void AppFilterIntegrationTest.testCountAppFilters() {
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to initialize correctly", dod.getRandomAppFilter());
        long count = AppFilter.countAppFilters();
        Assert.assertTrue("Counter for 'AppFilter' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppFilterIntegrationTest.testFindAppFilter() {
        AppFilter obj = dod.getRandomAppFilter();
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to initialize correctly", obj);
        Integer id = obj.getFilter();
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to provide an identifier", id);
        obj = AppFilter.findAppFilter(id);
        Assert.assertNotNull("Find method for 'AppFilter' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppFilter' returned the incorrect identifier", id, obj.getFilter());
    }
    
    @Test
    public void AppFilterIntegrationTest.testFindAllAppFilters() {
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to initialize correctly", dod.getRandomAppFilter());
        long count = AppFilter.countAppFilters();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppFilter', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppFilter> result = AppFilter.findAllAppFilters();
        Assert.assertNotNull("Find all method for 'AppFilter' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppFilter' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppFilterIntegrationTest.testFindAppFilterEntries() {
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to initialize correctly", dod.getRandomAppFilter());
        long count = AppFilter.countAppFilters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppFilter> result = AppFilter.findAppFilterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppFilter' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppFilter' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppFilterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to initialize correctly", dod.getRandomAppFilter());
        AppFilter obj = dod.getNewTransientAppFilter(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppFilter' identifier to be null", obj.getFilter());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AppFilter' identifier to no longer be null", obj.getFilter());
    }
    
    @Test
    public void AppFilterIntegrationTest.testRemove() {
        AppFilter obj = dod.getRandomAppFilter();
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to initialize correctly", obj);
        Integer id = obj.getFilter();
        Assert.assertNotNull("Data on demand for 'AppFilter' failed to provide an identifier", id);
        obj = AppFilter.findAppFilter(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppFilter' with identifier '" + id + "'", AppFilter.findAppFilter(id));
    }
    
}
