// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.AppModule;
import intranet.AppModuleDataOnDemand;
import intranet.AppModuleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppModuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppModuleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppModuleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppModuleIntegrationTest: @Transactional;
    
    @Autowired
    private AppModuleDataOnDemand AppModuleIntegrationTest.dod;
    
    @Test
    public void AppModuleIntegrationTest.testCountAppModules() {
        Assert.assertNotNull("Data on demand for 'AppModule' failed to initialize correctly", dod.getRandomAppModule());
        long count = AppModule.countAppModules();
        Assert.assertTrue("Counter for 'AppModule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppModuleIntegrationTest.testFindAppModule() {
        AppModule obj = dod.getRandomAppModule();
        Assert.assertNotNull("Data on demand for 'AppModule' failed to initialize correctly", obj);
        Integer id = obj.getModule();
        Assert.assertNotNull("Data on demand for 'AppModule' failed to provide an identifier", id);
        obj = AppModule.findAppModule(id);
        Assert.assertNotNull("Find method for 'AppModule' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppModule' returned the incorrect identifier", id, obj.getModule());
    }
    
    @Test
    public void AppModuleIntegrationTest.testFindAllAppModules() {
        Assert.assertNotNull("Data on demand for 'AppModule' failed to initialize correctly", dod.getRandomAppModule());
        long count = AppModule.countAppModules();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppModule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppModule> result = AppModule.findAllAppModules();
        Assert.assertNotNull("Find all method for 'AppModule' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppModule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppModuleIntegrationTest.testFindAppModuleEntries() {
        Assert.assertNotNull("Data on demand for 'AppModule' failed to initialize correctly", dod.getRandomAppModule());
        long count = AppModule.countAppModules();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppModule> result = AppModule.findAppModuleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppModule' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppModule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppModuleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppModule' failed to initialize correctly", dod.getRandomAppModule());
        AppModule obj = dod.getNewTransientAppModule(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppModule' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppModule' identifier to be null", obj.getModule());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AppModule' identifier to no longer be null", obj.getModule());
    }
    
    @Test
    public void AppModuleIntegrationTest.testRemove() {
        AppModule obj = dod.getRandomAppModule();
        Assert.assertNotNull("Data on demand for 'AppModule' failed to initialize correctly", obj);
        Integer id = obj.getModule();
        Assert.assertNotNull("Data on demand for 'AppModule' failed to provide an identifier", id);
        obj = AppModule.findAppModule(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppModule' with identifier '" + id + "'", AppModule.findAppModule(id));
    }
    
}
