// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.AppRight;
import intranet.AppRightDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AppRightDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppRightDataOnDemand: @Component;
    
    private Random AppRightDataOnDemand.rnd = new SecureRandom();
    
    private List<AppRight> AppRightDataOnDemand.data;
    
    public AppRight AppRightDataOnDemand.getNewTransientAppRight(int index) {
        AppRight obj = new AppRight();
        setDescription(obj, index);
        setIdent(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AppRightDataOnDemand.setDescription(AppRight obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void AppRightDataOnDemand.setIdent(AppRight obj, int index) {
        String ident = "ident_" + index;
        if (ident.length() > 70) {
            ident = new Random().nextInt(10) + ident.substring(1, 70);
        }
        obj.setIdent(ident);
    }
    
    public void AppRightDataOnDemand.setName(AppRight obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public AppRight AppRightDataOnDemand.getSpecificAppRight(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AppRight obj = data.get(index);
        Integer id = obj.getRight();
        return AppRight.findAppRight(id);
    }
    
    public AppRight AppRightDataOnDemand.getRandomAppRight() {
        init();
        AppRight obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getRight();
        return AppRight.findAppRight(id);
    }
    
    public boolean AppRightDataOnDemand.modifyAppRight(AppRight obj) {
        return false;
    }
    
    public void AppRightDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AppRight.findAppRightEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AppRight' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AppRight>();
        for (int i = 0; i < 10; i++) {
            AppRight obj = getNewTransientAppRight(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
