// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.AppSession;
import intranet.AppSessionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AppSessionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppSessionDataOnDemand: @Component;
    
    private Random AppSessionDataOnDemand.rnd = new SecureRandom();
    
    private List<AppSession> AppSessionDataOnDemand.data;
    
    public AppSession AppSessionDataOnDemand.getNewTransientAppSession(int index) {
        AppSession obj = new AppSession();
        setLastAction(obj, index);
        setLogin(obj, index);
        setLoginDate(obj, index);
        return obj;
    }
    
    public void AppSessionDataOnDemand.setLastAction(AppSession obj, int index) {
        Date lastAction = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastAction(lastAction);
    }
    
    public void AppSessionDataOnDemand.setLogin(AppSession obj, int index) {
        String login = "login_" + index;
        if (login.length() > 70) {
            login = login.substring(0, 70);
        }
        obj.setLogin(login);
    }
    
    public void AppSessionDataOnDemand.setLoginDate(AppSession obj, int index) {
        Date loginDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLoginDate(loginDate);
    }
    
    public AppSession AppSessionDataOnDemand.getSpecificAppSession(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AppSession obj = data.get(index);
        String id = obj.getSession();
        return AppSession.findAppSession(id);
    }
    
    public AppSession AppSessionDataOnDemand.getRandomAppSession() {
        init();
        AppSession obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getSession();
        return AppSession.findAppSession(id);
    }
    
    public boolean AppSessionDataOnDemand.modifyAppSession(AppSession obj) {
        return false;
    }
    
    public void AppSessionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AppSession.findAppSessionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AppSession' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AppSession>();
        for (int i = 0; i < 10; i++) {
            AppSession obj = getNewTransientAppSession(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
