// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.DataField;
import intranet.DataFieldDataOnDemand;
import intranet.DataFieldIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataFieldIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataFieldIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataFieldIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataFieldIntegrationTest: @Transactional;
    
    @Autowired
    private DataFieldDataOnDemand DataFieldIntegrationTest.dod;
    
    @Test
    public void DataFieldIntegrationTest.testCountDataFields() {
        Assert.assertNotNull("Data on demand for 'DataField' failed to initialize correctly", dod.getRandomDataField());
        long count = DataField.countDataFields();
        Assert.assertTrue("Counter for 'DataField' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataFieldIntegrationTest.testFindDataField() {
        DataField obj = dod.getRandomDataField();
        Assert.assertNotNull("Data on demand for 'DataField' failed to initialize correctly", obj);
        Integer id = obj.getFields();
        Assert.assertNotNull("Data on demand for 'DataField' failed to provide an identifier", id);
        obj = DataField.findDataField(id);
        Assert.assertNotNull("Find method for 'DataField' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DataField' returned the incorrect identifier", id, obj.getFields());
    }
    
    @Test
    public void DataFieldIntegrationTest.testFindAllDataFields() {
        Assert.assertNotNull("Data on demand for 'DataField' failed to initialize correctly", dod.getRandomDataField());
        long count = DataField.countDataFields();
        Assert.assertTrue("Too expensive to perform a find all test for 'DataField', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DataField> result = DataField.findAllDataFields();
        Assert.assertNotNull("Find all method for 'DataField' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DataField' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataFieldIntegrationTest.testFindDataFieldEntries() {
        Assert.assertNotNull("Data on demand for 'DataField' failed to initialize correctly", dod.getRandomDataField());
        long count = DataField.countDataFields();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DataField> result = DataField.findDataFieldEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DataField' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DataField' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataFieldIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DataField' failed to initialize correctly", dod.getRandomDataField());
        DataField obj = dod.getNewTransientDataField(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DataField' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DataField' identifier to be null", obj.getFields());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DataField' identifier to no longer be null", obj.getFields());
    }
    
    @Test
    public void DataFieldIntegrationTest.testRemove() {
        DataField obj = dod.getRandomDataField();
        Assert.assertNotNull("Data on demand for 'DataField' failed to initialize correctly", obj);
        Integer id = obj.getFields();
        Assert.assertNotNull("Data on demand for 'DataField' failed to provide an identifier", id);
        obj = DataField.findDataField(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DataField' with identifier '" + id + "'", DataField.findDataField(id));
    }
    
}
