// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.DataUser;
import intranet.DataUserDataOnDemand;
import intranet.DataUserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataUserIntegrationTest: @Transactional;
    
    @Autowired
    private DataUserDataOnDemand DataUserIntegrationTest.dod;
    
    @Test
    public void DataUserIntegrationTest.testCountDataUsers() {
        Assert.assertNotNull("Data on demand for 'DataUser' failed to initialize correctly", dod.getRandomDataUser());
        long count = DataUser.countDataUsers();
        Assert.assertTrue("Counter for 'DataUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataUserIntegrationTest.testFindDataUser() {
        DataUser obj = dod.getRandomDataUser();
        Assert.assertNotNull("Data on demand for 'DataUser' failed to initialize correctly", obj);
        Integer id = obj.getDataUser();
        Assert.assertNotNull("Data on demand for 'DataUser' failed to provide an identifier", id);
        obj = DataUser.findDataUser(id);
        Assert.assertNotNull("Find method for 'DataUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DataUser' returned the incorrect identifier", id, obj.getDataUser());
    }
    
    @Test
    public void DataUserIntegrationTest.testFindAllDataUsers() {
        Assert.assertNotNull("Data on demand for 'DataUser' failed to initialize correctly", dod.getRandomDataUser());
        long count = DataUser.countDataUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'DataUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DataUser> result = DataUser.findAllDataUsers();
        Assert.assertNotNull("Find all method for 'DataUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DataUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataUserIntegrationTest.testFindDataUserEntries() {
        Assert.assertNotNull("Data on demand for 'DataUser' failed to initialize correctly", dod.getRandomDataUser());
        long count = DataUser.countDataUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DataUser> result = DataUser.findDataUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DataUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DataUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DataUser' failed to initialize correctly", dod.getRandomDataUser());
        DataUser obj = dod.getNewTransientDataUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DataUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DataUser' identifier to be null", obj.getDataUser());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DataUser' identifier to no longer be null", obj.getDataUser());
    }
    
    @Test
    public void DataUserIntegrationTest.testRemove() {
        DataUser obj = dod.getRandomDataUser();
        Assert.assertNotNull("Data on demand for 'DataUser' failed to initialize correctly", obj);
        Integer id = obj.getDataUser();
        Assert.assertNotNull("Data on demand for 'DataUser' failed to provide an identifier", id);
        obj = DataUser.findDataUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DataUser' with identifier '" + id + "'", DataUser.findDataUser(id));
    }
    
}
