// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Fields;
import intranet.FieldsDataOnDemand;
import intranet.FieldsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FieldsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FieldsIntegrationTest: @Transactional;
    
    @Autowired
    private FieldsDataOnDemand FieldsIntegrationTest.dod;
    
    @Test
    public void FieldsIntegrationTest.testCountFieldses() {
        Assert.assertNotNull("Data on demand for 'Fields' failed to initialize correctly", dod.getRandomFields());
        long count = Fields.countFieldses();
        Assert.assertTrue("Counter for 'Fields' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FieldsIntegrationTest.testFindFields() {
        Fields obj = dod.getRandomFields();
        Assert.assertNotNull("Data on demand for 'Fields' failed to initialize correctly", obj);
        Integer id = obj.getIdfields();
        Assert.assertNotNull("Data on demand for 'Fields' failed to provide an identifier", id);
        obj = Fields.findFields(id);
        Assert.assertNotNull("Find method for 'Fields' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Fields' returned the incorrect identifier", id, obj.getIdfields());
    }
    
    @Test
    public void FieldsIntegrationTest.testFindAllFieldses() {
        Assert.assertNotNull("Data on demand for 'Fields' failed to initialize correctly", dod.getRandomFields());
        long count = Fields.countFieldses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Fields', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Fields> result = Fields.findAllFieldses();
        Assert.assertNotNull("Find all method for 'Fields' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Fields' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FieldsIntegrationTest.testFindFieldsEntries() {
        Assert.assertNotNull("Data on demand for 'Fields' failed to initialize correctly", dod.getRandomFields());
        long count = Fields.countFieldses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Fields> result = Fields.findFieldsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Fields' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Fields' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FieldsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Fields' failed to initialize correctly", dod.getRandomFields());
        Fields obj = dod.getNewTransientFields(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Fields' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Fields' identifier to be null", obj.getIdfields());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Fields' identifier to no longer be null", obj.getIdfields());
    }
    
    @Test
    public void FieldsIntegrationTest.testRemove() {
        Fields obj = dod.getRandomFields();
        Assert.assertNotNull("Data on demand for 'Fields' failed to initialize correctly", obj);
        Integer id = obj.getIdfields();
        Assert.assertNotNull("Data on demand for 'Fields' failed to provide an identifier", id);
        obj = Fields.findFields(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Fields' with identifier '" + id + "'", Fields.findFields(id));
    }
    
}
