// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Filter;
import intranet.FilterDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FilterDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FilterDataOnDemand: @Component;
    
    private Random FilterDataOnDemand.rnd = new SecureRandom();
    
    private List<Filter> FilterDataOnDemand.data;
    
    public Filter FilterDataOnDemand.getNewTransientFilter(int index) {
        Filter obj = new Filter();
        setClass1(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void FilterDataOnDemand.setClass1(Filter obj, int index) {
        String class1 = "class1_" + index;
        if (class1.length() > 75) {
            class1 = class1.substring(0, 75);
        }
        obj.setClass1(class1);
    }
    
    public void FilterDataOnDemand.setDescription(Filter obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void FilterDataOnDemand.setName(Filter obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public Filter FilterDataOnDemand.getSpecificFilter(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Filter obj = data.get(index);
        Integer id = obj.getIdfilter();
        return Filter.findFilter(id);
    }
    
    public Filter FilterDataOnDemand.getRandomFilter() {
        init();
        Filter obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getIdfilter();
        return Filter.findFilter(id);
    }
    
    public boolean FilterDataOnDemand.modifyFilter(Filter obj) {
        return false;
    }
    
    public void FilterDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Filter.findFilterEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Filter' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Filter>();
        for (int i = 0; i < 10; i++) {
            Filter obj = getNewTransientFilter(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
