// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Group;
import intranet.GroupDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect GroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GroupDataOnDemand: @Component;
    
    private Random GroupDataOnDemand.rnd = new SecureRandom();
    
    private List<Group> GroupDataOnDemand.data;
    
    public Group GroupDataOnDemand.getNewTransientGroup(int index) {
        Group obj = new Group();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void GroupDataOnDemand.setDescription(Group obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void GroupDataOnDemand.setName(Group obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = new Random().nextInt(10) + name.substring(1, 100);
        }
        obj.setName(name);
    }
    
    public Group GroupDataOnDemand.getSpecificGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Group obj = data.get(index);
        Integer id = obj.getIdgroup();
        return Group.findGroup(id);
    }
    
    public Group GroupDataOnDemand.getRandomGroup() {
        init();
        Group obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getIdgroup();
        return Group.findGroup(id);
    }
    
    public boolean GroupDataOnDemand.modifyGroup(Group obj) {
        return false;
    }
    
    public void GroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Group.findGroupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Group' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Group>();
        for (int i = 0; i < 10; i++) {
            Group obj = getNewTransientGroup(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
