// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Filter;
import intranet.FilterDataOnDemand;
import intranet.Group;
import intranet.GroupDataOnDemand;
import intranet.GroupFilter;
import intranet.GroupFilterDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GroupFilterDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GroupFilterDataOnDemand: @Component;
    
    private Random GroupFilterDataOnDemand.rnd = new SecureRandom();
    
    private List<GroupFilter> GroupFilterDataOnDemand.data;
    
    @Autowired
    private FilterDataOnDemand GroupFilterDataOnDemand.filterDataOnDemand;
    
    @Autowired
    private GroupDataOnDemand GroupFilterDataOnDemand.groupDataOnDemand;
    
    public GroupFilter GroupFilterDataOnDemand.getNewTransientGroupFilter(int index) {
        GroupFilter obj = new GroupFilter();
        setIdfilter(obj, index);
        setIdgroup(obj, index);
        return obj;
    }
    
    public void GroupFilterDataOnDemand.setIdfilter(GroupFilter obj, int index) {
        Filter idfilter = filterDataOnDemand.getRandomFilter();
        obj.setIdfilter(idfilter);
    }
    
    public void GroupFilterDataOnDemand.setIdgroup(GroupFilter obj, int index) {
        Group idgroup = groupDataOnDemand.getRandomGroup();
        obj.setIdgroup(idgroup);
    }
    
    public GroupFilter GroupFilterDataOnDemand.getSpecificGroupFilter(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GroupFilter obj = data.get(index);
        Integer id = obj.getIdgroupFilter();
        return GroupFilter.findGroupFilter(id);
    }
    
    public GroupFilter GroupFilterDataOnDemand.getRandomGroupFilter() {
        init();
        GroupFilter obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getIdgroupFilter();
        return GroupFilter.findGroupFilter(id);
    }
    
    public boolean GroupFilterDataOnDemand.modifyGroupFilter(GroupFilter obj) {
        return false;
    }
    
    public void GroupFilterDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = GroupFilter.findGroupFilterEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GroupFilter' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GroupFilter>();
        for (int i = 0; i < 10; i++) {
            GroupFilter obj = getNewTransientGroupFilter(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
