// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.ModuleGroups;
import intranet.ModuleGroupsDataOnDemand;
import intranet.ModuleGroupsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ModuleGroupsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ModuleGroupsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ModuleGroupsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ModuleGroupsIntegrationTest: @Transactional;
    
    @Autowired
    private ModuleGroupsDataOnDemand ModuleGroupsIntegrationTest.dod;
    
    @Test
    public void ModuleGroupsIntegrationTest.testCountModuleGroupses() {
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to initialize correctly", dod.getRandomModuleGroups());
        long count = ModuleGroups.countModuleGroupses();
        Assert.assertTrue("Counter for 'ModuleGroups' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ModuleGroupsIntegrationTest.testFindModuleGroups() {
        ModuleGroups obj = dod.getRandomModuleGroups();
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to initialize correctly", obj);
        Integer id = obj.getIdmoduleAccess();
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to provide an identifier", id);
        obj = ModuleGroups.findModuleGroups(id);
        Assert.assertNotNull("Find method for 'ModuleGroups' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ModuleGroups' returned the incorrect identifier", id, obj.getIdmoduleAccess());
    }
    
    @Test
    public void ModuleGroupsIntegrationTest.testFindAllModuleGroupses() {
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to initialize correctly", dod.getRandomModuleGroups());
        long count = ModuleGroups.countModuleGroupses();
        Assert.assertTrue("Too expensive to perform a find all test for 'ModuleGroups', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ModuleGroups> result = ModuleGroups.findAllModuleGroupses();
        Assert.assertNotNull("Find all method for 'ModuleGroups' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ModuleGroups' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ModuleGroupsIntegrationTest.testFindModuleGroupsEntries() {
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to initialize correctly", dod.getRandomModuleGroups());
        long count = ModuleGroups.countModuleGroupses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ModuleGroups> result = ModuleGroups.findModuleGroupsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ModuleGroups' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ModuleGroups' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ModuleGroupsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to initialize correctly", dod.getRandomModuleGroups());
        ModuleGroups obj = dod.getNewTransientModuleGroups(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ModuleGroups' identifier to be null", obj.getIdmoduleAccess());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ModuleGroups' identifier to no longer be null", obj.getIdmoduleAccess());
    }
    
    @Test
    public void ModuleGroupsIntegrationTest.testRemove() {
        ModuleGroups obj = dod.getRandomModuleGroups();
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to initialize correctly", obj);
        Integer id = obj.getIdmoduleAccess();
        Assert.assertNotNull("Data on demand for 'ModuleGroups' failed to provide an identifier", id);
        obj = ModuleGroups.findModuleGroups(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ModuleGroups' with identifier '" + id + "'", ModuleGroups.findModuleGroups(id));
    }
    
}
