// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.ModuleAction;
import intranet.ModuleActionDataOnDemand;
import intranet.ModuleActionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ModuleActionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ModuleActionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ModuleActionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ModuleActionIntegrationTest: @Transactional;
    
    @Autowired
    private ModuleActionDataOnDemand ModuleActionIntegrationTest.dod;
    
    @Test
    public void ModuleActionIntegrationTest.testCountModuleActions() {
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to initialize correctly", dod.getRandomModuleAction());
        long count = ModuleAction.countModuleActions();
        Assert.assertTrue("Counter for 'ModuleAction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ModuleActionIntegrationTest.testFindModuleAction() {
        ModuleAction obj = dod.getRandomModuleAction();
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to initialize correctly", obj);
        Integer id = obj.getAction();
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to provide an identifier", id);
        obj = ModuleAction.findModuleAction(id);
        Assert.assertNotNull("Find method for 'ModuleAction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ModuleAction' returned the incorrect identifier", id, obj.getAction());
    }
    
    @Test
    public void ModuleActionIntegrationTest.testFindAllModuleActions() {
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to initialize correctly", dod.getRandomModuleAction());
        long count = ModuleAction.countModuleActions();
        Assert.assertTrue("Too expensive to perform a find all test for 'ModuleAction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ModuleAction> result = ModuleAction.findAllModuleActions();
        Assert.assertNotNull("Find all method for 'ModuleAction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ModuleAction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ModuleActionIntegrationTest.testFindModuleActionEntries() {
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to initialize correctly", dod.getRandomModuleAction());
        long count = ModuleAction.countModuleActions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ModuleAction> result = ModuleAction.findModuleActionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ModuleAction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ModuleAction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ModuleActionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to initialize correctly", dod.getRandomModuleAction());
        ModuleAction obj = dod.getNewTransientModuleAction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ModuleAction' identifier to be null", obj.getAction());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ModuleAction' identifier to no longer be null", obj.getAction());
    }
    
    @Test
    public void ModuleActionIntegrationTest.testRemove() {
        ModuleAction obj = dod.getRandomModuleAction();
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to initialize correctly", obj);
        Integer id = obj.getAction();
        Assert.assertNotNull("Data on demand for 'ModuleAction' failed to provide an identifier", id);
        obj = ModuleAction.findModuleAction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ModuleAction' with identifier '" + id + "'", ModuleAction.findModuleAction(id));
    }
    
}
