// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Objects;
import intranet.ObjectsDataOnDemand;
import intranet.ObjectsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ObjectsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ObjectsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ObjectsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ObjectsIntegrationTest: @Transactional;
    
    @Autowired
    private ObjectsDataOnDemand ObjectsIntegrationTest.dod;
    
    @Test
    public void ObjectsIntegrationTest.testCountObjectses() {
        Assert.assertNotNull("Data on demand for 'Objects' failed to initialize correctly", dod.getRandomObjects());
        long count = Objects.countObjectses();
        Assert.assertTrue("Counter for 'Objects' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ObjectsIntegrationTest.testFindObjects() {
        Objects obj = dod.getRandomObjects();
        Assert.assertNotNull("Data on demand for 'Objects' failed to initialize correctly", obj);
        Integer id = obj.getIdobject();
        Assert.assertNotNull("Data on demand for 'Objects' failed to provide an identifier", id);
        obj = Objects.findObjects(id);
        Assert.assertNotNull("Find method for 'Objects' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Objects' returned the incorrect identifier", id, obj.getIdobject());
    }
    
    @Test
    public void ObjectsIntegrationTest.testFindAllObjectses() {
        Assert.assertNotNull("Data on demand for 'Objects' failed to initialize correctly", dod.getRandomObjects());
        long count = Objects.countObjectses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Objects', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Objects> result = Objects.findAllObjectses();
        Assert.assertNotNull("Find all method for 'Objects' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Objects' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ObjectsIntegrationTest.testFindObjectsEntries() {
        Assert.assertNotNull("Data on demand for 'Objects' failed to initialize correctly", dod.getRandomObjects());
        long count = Objects.countObjectses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Objects> result = Objects.findObjectsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Objects' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Objects' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ObjectsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Objects' failed to initialize correctly", dod.getRandomObjects());
        Objects obj = dod.getNewTransientObjects(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Objects' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Objects' identifier to be null", obj.getIdobject());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Objects' identifier to no longer be null", obj.getIdobject());
    }
    
    @Test
    public void ObjectsIntegrationTest.testRemove() {
        Objects obj = dod.getRandomObjects();
        Assert.assertNotNull("Data on demand for 'Objects' failed to initialize correctly", obj);
        Integer id = obj.getIdobject();
        Assert.assertNotNull("Data on demand for 'Objects' failed to provide an identifier", id);
        obj = Objects.findObjects(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Objects' with identifier '" + id + "'", Objects.findObjects(id));
    }
    
}
