// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Group;
import intranet.GroupDataOnDemand;
import intranet.Privacities;
import intranet.PrivacitiesDataOnDemand;
import intranet.User;
import intranet.UserDataOnDemand;
import intranet.UserInfo;
import intranet.UserInfoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PrivacitiesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PrivacitiesDataOnDemand: @Component;
    
    private Random PrivacitiesDataOnDemand.rnd = new SecureRandom();
    
    private List<Privacities> PrivacitiesDataOnDemand.data;
    
    @Autowired
    private GroupDataOnDemand PrivacitiesDataOnDemand.groupDataOnDemand;
    
    @Autowired
    private UserInfoDataOnDemand PrivacitiesDataOnDemand.userInfoDataOnDemand;
    
    @Autowired
    private UserDataOnDemand PrivacitiesDataOnDemand.userDataOnDemand;
    
    public Privacities PrivacitiesDataOnDemand.getNewTransientPrivacities(int index) {
        Privacities obj = new Privacities();
        setIdgroup(obj, index);
        setIdinfo(obj, index);
        setIduser(obj, index);
        return obj;
    }
    
    public void PrivacitiesDataOnDemand.setIdgroup(Privacities obj, int index) {
        Group idgroup = groupDataOnDemand.getRandomGroup();
        obj.setIdgroup(idgroup);
    }
    
    public void PrivacitiesDataOnDemand.setIdinfo(Privacities obj, int index) {
        UserInfo idinfo = userInfoDataOnDemand.getRandomUserInfo();
        obj.setIdinfo(idinfo);
    }
    
    public void PrivacitiesDataOnDemand.setIduser(Privacities obj, int index) {
        User iduser = userDataOnDemand.getRandomUser();
        obj.setIduser(iduser);
    }
    
    public Privacities PrivacitiesDataOnDemand.getSpecificPrivacities(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Privacities obj = data.get(index);
        Integer id = obj.getIdprivacity();
        return Privacities.findPrivacities(id);
    }
    
    public Privacities PrivacitiesDataOnDemand.getRandomPrivacities() {
        init();
        Privacities obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getIdprivacity();
        return Privacities.findPrivacities(id);
    }
    
    public boolean PrivacitiesDataOnDemand.modifyPrivacities(Privacities obj) {
        return false;
    }
    
    public void PrivacitiesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Privacities.findPrivacitiesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Privacities' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Privacities>();
        for (int i = 0; i < 10; i++) {
            Privacities obj = getNewTransientPrivacities(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
