// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Privacity;
import intranet.PrivacityDataOnDemand;
import intranet.PrivacityIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrivacityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrivacityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrivacityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrivacityIntegrationTest: @Transactional;
    
    @Autowired
    private PrivacityDataOnDemand PrivacityIntegrationTest.dod;
    
    @Test
    public void PrivacityIntegrationTest.testCountPrivacitys() {
        Assert.assertNotNull("Data on demand for 'Privacity' failed to initialize correctly", dod.getRandomPrivacity());
        long count = Privacity.countPrivacitys();
        Assert.assertTrue("Counter for 'Privacity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrivacityIntegrationTest.testFindPrivacity() {
        Privacity obj = dod.getRandomPrivacity();
        Assert.assertNotNull("Data on demand for 'Privacity' failed to initialize correctly", obj);
        Integer id = obj.getIdprivacity();
        Assert.assertNotNull("Data on demand for 'Privacity' failed to provide an identifier", id);
        obj = Privacity.findPrivacity(id);
        Assert.assertNotNull("Find method for 'Privacity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Privacity' returned the incorrect identifier", id, obj.getIdprivacity());
    }
    
    @Test
    public void PrivacityIntegrationTest.testFindAllPrivacitys() {
        Assert.assertNotNull("Data on demand for 'Privacity' failed to initialize correctly", dod.getRandomPrivacity());
        long count = Privacity.countPrivacitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Privacity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Privacity> result = Privacity.findAllPrivacitys();
        Assert.assertNotNull("Find all method for 'Privacity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Privacity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrivacityIntegrationTest.testFindPrivacityEntries() {
        Assert.assertNotNull("Data on demand for 'Privacity' failed to initialize correctly", dod.getRandomPrivacity());
        long count = Privacity.countPrivacitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Privacity> result = Privacity.findPrivacityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Privacity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Privacity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrivacityIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Privacity' failed to initialize correctly", dod.getRandomPrivacity());
        Privacity obj = dod.getNewTransientPrivacity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Privacity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Privacity' identifier to be null", obj.getIdprivacity());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Privacity' identifier to no longer be null", obj.getIdprivacity());
    }
    
    @Test
    public void PrivacityIntegrationTest.testRemove() {
        Privacity obj = dod.getRandomPrivacity();
        Assert.assertNotNull("Data on demand for 'Privacity' failed to initialize correctly", obj);
        Integer id = obj.getIdprivacity();
        Assert.assertNotNull("Data on demand for 'Privacity' failed to provide an identifier", id);
        obj = Privacity.findPrivacity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Privacity' with identifier '" + id + "'", Privacity.findPrivacity(id));
    }
    
}
