// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Session;
import intranet.SessionDataOnDemand;
import intranet.SessionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SessionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SessionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SessionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SessionIntegrationTest: @Transactional;
    
    @Autowired
    private SessionDataOnDemand SessionIntegrationTest.dod;
    
    @Test
    public void SessionIntegrationTest.testCountSessions() {
        Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        long count = Session.countSessions();
        Assert.assertTrue("Counter for 'Session' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SessionIntegrationTest.testFindSession() {
        Session obj = dod.getRandomSession();
        Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", obj);
        String id = obj.getIdsession();
        Assert.assertNotNull("Data on demand for 'Session' failed to provide an identifier", id);
        obj = Session.findSession(id);
        Assert.assertNotNull("Find method for 'Session' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Session' returned the incorrect identifier", id, obj.getIdsession());
    }
    
    @Test
    public void SessionIntegrationTest.testFindAllSessions() {
        Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        long count = Session.countSessions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Session', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Session> result = Session.findAllSessions();
        Assert.assertNotNull("Find all method for 'Session' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Session' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SessionIntegrationTest.testFindSessionEntries() {
        Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        long count = Session.countSessions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Session> result = Session.findSessionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Session' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Session' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SessionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        Session obj = dod.getNewTransientSession(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Session' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Session' identifier to be null", obj.getIdsession());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Session' identifier to no longer be null", obj.getIdsession());
    }
    
    @Test
    public void SessionIntegrationTest.testRemove() {
        Session obj = dod.getRandomSession();
        Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", obj);
        String id = obj.getIdsession();
        Assert.assertNotNull("Data on demand for 'Session' failed to provide an identifier", id);
        obj = Session.findSession(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Session' with identifier '" + id + "'", Session.findSession(id));
    }
    
}
