// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.Session;
import intranet.SessionDataOnDemand;
import intranet.User;
import intranet.UserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SessionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SessionDataOnDemand: @Component;
    
    private Random SessionDataOnDemand.rnd = new SecureRandom();
    
    private List<Session> SessionDataOnDemand.data;
    
    @Autowired
    private UserDataOnDemand SessionDataOnDemand.userDataOnDemand;
    
    public Session SessionDataOnDemand.getNewTransientSession(int index) {
        Session obj = new Session();
        setIduser(obj, index);
        setLastAction(obj, index);
        setLoginDate(obj, index);
        return obj;
    }
    
    public void SessionDataOnDemand.setIduser(Session obj, int index) {
        User iduser = userDataOnDemand.getRandomUser();
        obj.setIduser(iduser);
    }
    
    public void SessionDataOnDemand.setLastAction(Session obj, int index) {
        Date lastAction = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastAction(lastAction);
    }
    
    public void SessionDataOnDemand.setLoginDate(Session obj, int index) {
        Date loginDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLoginDate(loginDate);
    }
    
    public Session SessionDataOnDemand.getSpecificSession(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Session obj = data.get(index);
        String id = obj.getIdsession();
        return Session.findSession(id);
    }
    
    public Session SessionDataOnDemand.getRandomSession() {
        init();
        Session obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getIdsession();
        return Session.findSession(id);
    }
    
    public boolean SessionDataOnDemand.modifySession(Session obj) {
        return false;
    }
    
    public void SessionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Session.findSessionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Session' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Session>();
        for (int i = 0; i < 10; i++) {
            Session obj = getNewTransientSession(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
