// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package intranet;

import intranet.UserGroups;
import intranet.UserGroupsDataOnDemand;
import intranet.UserGroupsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserGroupsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserGroupsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserGroupsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserGroupsIntegrationTest: @Transactional;
    
    @Autowired
    private UserGroupsDataOnDemand UserGroupsIntegrationTest.dod;
    
    @Test
    public void UserGroupsIntegrationTest.testCountUserGroupses() {
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to initialize correctly", dod.getRandomUserGroups());
        long count = UserGroups.countUserGroupses();
        Assert.assertTrue("Counter for 'UserGroups' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserGroupsIntegrationTest.testFindUserGroups() {
        UserGroups obj = dod.getRandomUserGroups();
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to initialize correctly", obj);
        Integer id = obj.getIduserGroups();
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to provide an identifier", id);
        obj = UserGroups.findUserGroups(id);
        Assert.assertNotNull("Find method for 'UserGroups' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserGroups' returned the incorrect identifier", id, obj.getIduserGroups());
    }
    
    @Test
    public void UserGroupsIntegrationTest.testFindAllUserGroupses() {
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to initialize correctly", dod.getRandomUserGroups());
        long count = UserGroups.countUserGroupses();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserGroups', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserGroups> result = UserGroups.findAllUserGroupses();
        Assert.assertNotNull("Find all method for 'UserGroups' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserGroups' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserGroupsIntegrationTest.testFindUserGroupsEntries() {
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to initialize correctly", dod.getRandomUserGroups());
        long count = UserGroups.countUserGroupses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserGroups> result = UserGroups.findUserGroupsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserGroups' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserGroups' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserGroupsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to initialize correctly", dod.getRandomUserGroups());
        UserGroups obj = dod.getNewTransientUserGroups(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserGroups' identifier to be null", obj.getIduserGroups());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserGroups' identifier to no longer be null", obj.getIduserGroups());
    }
    
    @Test
    public void UserGroupsIntegrationTest.testRemove() {
        UserGroups obj = dod.getRandomUserGroups();
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to initialize correctly", obj);
        Integer id = obj.getIduserGroups();
        Assert.assertNotNull("Data on demand for 'UserGroups' failed to provide an identifier", id);
        obj = UserGroups.findUserGroups(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserGroups' with identifier '" + id + "'", UserGroups.findUserGroups(id));
    }
    
}
