// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package models;

import models.AppRight;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppRight_Roo_Configurable {
    
    declare @type: AppRight: @Configurable;
    
}
