// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package models;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import models.ModuleAction;

import org.springframework.transaction.annotation.Transactional;

privileged aspect ModuleAction_Roo_Jpa_ActiveRecord {
    
   
}
